#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144.00 --output DVI-D-0 --mode 1920x1080 --rate 60.00 --left-of HDMI-0 &
xrandr --dpi 81 &
~/.fehbg &
picom &
nvidia-settings --load-config-only &
xset m 0 0 &
xinput --set-prop 8 "libinput Accel Speed" -0.7 &
$HOME/.config/polybar/launch.sh

bspc monitor HDMI-0 -d I II III IV V VI
bspc monitor DVI-D-0 -d VII VII IX X XI XII

bspc config border_width        3
bspc config window_gap          16
bspc config top_padding 	16

bspc config split_ratio         0.6

bspc config normal_border_color '#1c1c1c'
bspc config active_border_color '#1c1c1c'
bspc config focused_border_color '#1c1c1c'

# bspc rule -a kitty state=floating
bspc rule -a lxappearance state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a spotify state=floating
